routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/threads', 'ThreadsController@index')->name('threads');
Route::get('/threads/create', 'ThreadsController@create');
Route::get('/threads/search', 'SearchController@show');
Route::get('/threads/{channel}/{thread}', 'ThreadsController@show');
Route::patch('threads/{channel}/{thread}', 'ThreadsController@update')->name('threads.update');

Route::post('locked-threads/{thread}', 'LockedController@store')->name('locked-threads.store')->middleware('admin');
Route::delete('locked-threads/{thread}', 'LockedController@destroy')->name('locked-threads.destroy')->middleware('admin');

Route::delete('/threads/{channel}/{thread}', 'ThreadsController@destroy');
Route::post('/threads', 'ThreadsController@store')->middleware('must-be-confirmed');
Route::get('/threads/{channel}', 'ThreadsController@index');

Route::get('/threads/{channel}/{thread}/replies', 'RepliesController@index');
Route::post('/threads/{channel}/{thread}/replies', 'RepliesController@store');

Route::post('/threads/{channel}/{thread}/subscriptions', 'ThreadSubscriptionsController@store')->middleware('auth');
Route::delete('/threads/{channel}/{thread}/subscriptions', 'ThreadSubscriptionsController@destroy')->middleware('auth');

Route::patch('/replies/{reply}', 'RepliesController@update');
Route::delete('/replies/{reply}', 'RepliesController@destroy')->name('replies.destroy');

Route::post('/replies/{reply}/favorites', 'FavoritesController@store');
Route::delete('/replies/{reply}/favorites', 'FavoritesController@destroy');

Route::get('/profiles/{user}', 'ProfilesController@show')->name('profile');
Route::get('/profiles/{user}/notifications', 'UserNofiticationsController@index');
Route::delete('/profiles/{user}/notifications/{notification}', 'UserNofiticationsController@destroy');

Route::get('api/users', 'Api\UserController@index');
Route::post('/api/users/{user}/avatar', 'UserAvatarController@store')->middleware('auth')->name('avatar_path');

Route::get('/register/confirm', 'Api\RegisterConfirmationController@index')->name('register.confirm');

Route::post('/replies/{reply}/best', 'BestRepliesController@store')->name('best-replies.store');

app/Thread.php
<?php

namespace Forum;

use Forum\Events\ThreadReceivedNewReply;
use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;

class Thread extends Model
{
    use RecordsActivity, Searchable;

    protected $guarded = [];
    protected $with = ['creator', 'channel'];
    protected $appends = ['isSubscribedTo'];
    protected $casts = ['locked' => 'boolean'];
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('replyCount', function ($builder) {
            $builder->withCount('replies');
        });

        static::deleting(function ($thread) {
            $thread->replies->each->delete();
        });

        static::created(function ($thread) {
            $thread->update(['slug' => $thread->title]);
        });

    }

    public function path()
    {
        return "/threads/{$this->channel->slug}/{$this->slug}";
    }

    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /**
     * @param $reply
     * @return Model
     */
    public function addReply($reply)
    {
        $reply = $this->replies()->create($reply);
        event(new ThreadReceivedNewReply($reply));
        return $reply;
    }

    public function channel()
    {
        return $this->belongsTo(Channel::class);
    }

    public function scopeFilter($query, $filters)
    {
        return $filters->apply($query);
    }

    public function subscribe($userId = null)
    {
        $this->subscriptions()->create([
            'user_id' => $userId ?: auth()->id()
        ]);
    }

    public function subscriptions()
    {
        return $this->hasMany(ThreadSubscription::class);
    }

    public function unsubscribe($userId = null)
    {
        $this->subscriptions()
            ->where('user_id', $userId ?: auth()->id())
            ->delete();
    }

    public function getIsSubscribedToAttribute()
    {
        return $this->subscriptions()->where('user_id', auth()->id())->exists();
    }

    public function visits()
    {
        return new Visits($this);
    }

    public function hasUpdateFor($user)
    {
        $key = $user->visitedThreadCacheKey($this);
        return $this->updated_at > cache($key);
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function setSlugAttribute($value)
    {
        $slug = str_slug($value);
        if (static::whereSlug($slug)->exists()) {
            $slug = "{$slug}-" . $this->id;
        }

        $this->attributes['slug'] = $slug;
    }

    public function markBestReply(Reply $reply)
    {
        $this->update(['best_reply_id' => $reply->id]);
    }

    public function lock()
    {
        $this->update(['locked' => true]);
    }
    public function unlock()
    {
        $this->update(['locked' => false]);
    }
}

app/Http/Controllers/ThreadsController.php
<?php

namespace Forum\Http\Controllers;


use Exception;
use Forum\Channel;
use Forum\Filters\ThreadFilters;
use Forum\Rules\Recaptcha;
use Forum\Thread;
use Forum\Trending;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Validation\ValidationException;

class ThreadsController extends Controller
{
    /**
     * ThreadsController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
//        \Redis::del('trending_threads');
    }

    /**
     * Display a listing of the resource.
     *
     * @param Channel $channel
     * @param ThreadFilters $filters
     * @param Trending $trending
     * @return Response
     */
    public function index(Channel $channel, ThreadFilters $filters, Trending $trending)
    {
        $threads = $this->getThreads($channel, $filters);
        if (request()->wantsJson()) return $threads;
        return view('threads.index', [
            'threads' => $threads,
            'trending' => $trending->get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {

        return view('threads.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @param Recaptcha $recaptcha
     * @return Response
     * @throws ValidationException
     */
    public function store(Request $request, Recaptcha $recaptcha)
    {
        $this->validate($request, [
            'title' => 'required|spamfree',
            'body' => 'required|spamfree',
            'channel_id' => 'required|exists:channels,id',
            'g-recaptcha-response' => [$recaptcha]
        ]);

        $thread = Thread::create([
            'user_id' => auth()->id(),
            'channel_id' => request('channel_id'),
            'title' => request('title'),
            'body' => request('body')
        ]);

        return redirect($thread->path())->with('flash', 'Your thread has been published!');
    }

    /**
     * Display the specified resource.
     *
     * @param $channelId
     * @param Thread $thread
     * @param Trending $trending
     * @return Response
     */
    public function show($channelId, Thread $thread, Trending $trending)
    {
        if (auth()->check()) {
            auth()->user()->read($thread);
        }
        $trending->push($thread);
        $thread->increment('visits');
//        $thread->visits()->record();
        return view('threads.show', compact('thread'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Thread $thread
     * @return Response
     */
    public function edit(Thread $thread)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param $channel
     * @param Thread $thread
     * @return Thread
     * @throws AuthorizationException
     */
    public function update($channel, Thread $thread)
    {
        $this->authorize('update', $thread);
        $thread->update(request()->validate(['title' =>'required', 'body' =>'required']));
        return $thread;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $channel
     * @param Thread $thread
     * @return void
     * @throws Exception
     */
    public function destroy($channel, Thread $thread)
    {
        $this->authorize('update', $thread);

        $thread->delete();
        if (request()->wantsJson()) {
            return response([], 204);
        }
        return redirect('/threads');
    }

    /**
     * @param Channel $channel
     * @param ThreadFilters $filters
     * @return mixed
     */
    protected function getThreads(Channel $channel, ThreadFilters $filters)
    {
        $threads = Thread::latest()->filter($filters);
        if ($channel->exists) {
            $threads->where('channel_id', $channel->id);
        }
        return $threads->paginate(25);
    }

}

resources/views/threads/_list.blade.php
@forelse($threads as $thread)
    <div class="card mb-3">
        <div class="card-header d-flex justify-content-between">
            <div class="d-flex">
                <h4>
                    <a href="{{ $thread->path() }}" class="text-capitalize">
                        @if(auth()->check() && $thread->hasUpdateFor(auth()->user()))
                            <strong>{{ $thread->title }}</strong>
                        @else
                            {{ $thread->title }}
                        @endif
                    </a>
                    <br>
                    <span class="small">Posted By: <a href="{{ route('profile', $thread->creator) }}">{{ $thread->creator->name }}</a></span>
                </h4>
            </div>
            <div><a href="{{ $thread->path() }}">{{ $thread->replies_count }} {{ str_plural('reply', $thread->replies_count) }}</a></div>
        </div>
        <div class="card-body">
            <div class="body">{{ $thread->body }}</div>
        </div><!-- end of card body -->
        <div class="card-footer">
            {{ $thread->visits }} visits
        </div>
    </div><!-- end of card -->
@empty
    <p class="text-center">There are no relevant results at this time.</p>
@endforelse

resources/views/threads/_question.blade.php
{{-- Editing the quesiton--}}
<div class="card" v-if="editing">

    <div class="card-header">

        <div class="form-group">
            <label for="Title">Title:</label>
            <input type="text" class="form-control" id="Title" v-model="form.title">
        </div>

    </div>

    <div class="card-body">
        <textarea rows="10" class="form-control" v-model="form.body"></textarea>
    </div>

    <div class="card-footer d-flex justify-content-between">
        <div>
            <button class="btn btn-info" @click="editing = true" v-show="!editing">Edit</button>
            <button class="btn btn-primary" @click="update">Update</button>
            <button class="btn btn-link" @click="resetForm">Cancel</button>
        </div>

        @can('update', $thread)
            <form action="{{$thread->path() }}" method="post">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-link">Delete thread</button>
            </form>
        @endcan
    </div>

</div><!-- end of 1st card -->


{{-- Viewing the quesiton--}}
<div class="card" v-else>

    <div class="card-header d-flex justify-content-between">

        <img src="{{ $thread->creator->avatar_path }}" alt="" width="100" height="100">

        <h3 class="text-capitalize">
            <span v-text="title"></span><br>
            <small class="small">
                Posted by: <a href="/profiles/{{ $thread->creator->name }}"
                              class="text-capitalize">{{ $thread->creator->name }}</a>
            </small>
        </h3>

        @can('update', $thread)
            <form action="{{ $thread->path() }}" method="post">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-link">Delete Thread</button>
            </form>
        @endcan

    </div>

    <div class="card-body" v-text="body"></div>

    <div class="card-footer" v-if="authorize('owns', thread)">
        <button class="btn btn-info" @click="editing = true">Edit</button>
    </div>

</div><!-- end of 1st card -->

resources/views/threads/create.blade.php
@extends('layouts.app')
@section('head')
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
@endsection
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Create a New Thread</div>

                    <div class="card-body">
                        <form action="/threads" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="channel_id">Choose a Channel:</label>
                                <select name="channel_id" id="channel_id" class="form-control" required>
                                    <option value="">Choose one...</option>
                                    @foreach($channels as $channel)
                                        <option
                                            value="{{ $channel->id }}" {{ old('channel_id') == $channel->id ? 'selected' : '' }}>{{ $channel->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="title">Title:</label>
                                <input type="text" class="form-control" id="title" name="title" placeholder="Title..."
                                       value="{{ old('title') }}" required>
                            </div>
                            <div class="form-group">
                                <textarea name="body" class="form-control" id="body" cols="" rows="8"
                                          placeholder="Description..." required>{{ old('body') }}</textarea>
                            </div>
                            <div class="form-group">
                                <div class="g-recaptcha" data-sitekey="6Ldc9LoUAAAAAP42lhWE-y7z16ECCH-d0JNpQ0OA"></div>
                            </div>
                            <button type="submit" class="btn btn-primary">Published</button>
                        </form>
                        @if(count($errors))
                            <ul class="alert alert-danger mt-3">
                                @foreach($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/threads/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        <div class="row">

            <div class="col-md-8">

                @include('threads._list')

                {{ $threads->render() }}

            </div><!-- end of col-md-8 -->

            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <div class="card-title">Search</div>
                        <form action="/threads/search" method="get">
                            <div class="form-group">
                                <input type="text" placeholder="Search for something..." name="q" class="form-control">
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary" type="submit">Search</button>
                            </div>
                        </form>
                    </div>
                </div><!-- end of search card -->

                @if(count($trending))
                    <div class="card">
                        <div class="card-header">
                            Trending Threads
                        </div>
                        <ul class="list-group list-group-flush">
                            @forelse($trending as $trend)
                                <li class="list-group-item"><a href="{{ url($trend->path) }}">{{ $trend->title }}</a>
                                </li>
                            @empty
                                <li class="list-group-item">no data</li>
                            @endforelse
                        </ul>
                    </div>
                @endif

            </div>

        </div><!-- end of row -->

    </div><!-- end of container -->
@endsection

resources/views/threads/reply.blade.php
<reply :attributes="{{ $reply }}" inline-template v-cloak>
    <div id="reply-{{ $reply->id }}" class="card my-4">
        <div class="card-header">
            <div class="level d-flex justify-content-between">
                <h5>
                    <a href="/profiles/{{ $reply->owner->name }}">{{ $reply->owner->name }}</a>
                    said {{ $reply->created_at->diffForHumans() }}...
                </h5>
                @if(Auth::check())
                    <div>
                        <favorite :reply="{{ $reply }}"></favorite>
                    </div>
                @endif
            </div>
        </div>
        <div class="card-body">
            <div v-if="editing">
                <div class="form-group">
                    <textarea class="form-control" v-model="body"></textarea>
                </div>
                <button class="btn btn-sm btn-primary" @click="update">Update</button>
                <button class="btn btn-sm btn-link" @click="editing = false">Cancel</button>
            </div>
            <div v-else v-text="body"></div>
        </div>
        @can('update', $reply)
            <div class="card-footer d-flex">
                <button class="btn btn-sm btn-info mr-2" @click="editing = true">Edit</button>
                <button class="btn btn-sm btn-danger mr-2" @click="destroy">Delete</button>
            </div>
        @endcan

    </div>
</reply>

resources/views/threads/show.blade.php
@extends('layouts.app')

@section('head')
    <link rel="stylesheet" href="{{ asset('css/vendor/jquery.atwho.css') }}">
@endsection

@section('content')
    <thread-view :thread="{{ $thread }}" inline-template>

        <div class="container">

            <div class="row">

                <div class="col-md-8" v-cloak>

                    @include('threads._question')

                    <replies @added="repliesCount++" @removed="repliesCount--"></replies>

                </div><!-- end of col-md-8 -->

                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <p>
                                This thread was published {{ $thread->created_at->diffForHumans() }} by
                                <a href="#">{{ $thread->creator->name }}</a>, and currently
                                has <span
                                    v-text="repliesCount"></span> {{ str_plural('comment', $thread->replies_count) }}.
                            </p>
                            <p>
                                <subscribe-button
                                    :active="{{ json_encode($thread->isSubscribedTo) }}" v-if="signedIn"></subscribe-button>
                                <button class="btn btn-danger" v-if="authorize('isAdmin')"  @click="ToggleLock" v-text="locked ? 'Unlock' : 'Lock'">Lock</button>
                            </p>
                        </div>
                    </div>
                </div>
            </div><!-- end of row -->
        </div><!-- end of container -->
    </thread-view>
@endsection